version: '3.8'

services:
  db:
    image: postgres:14
    container_name: goGate-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - goGate-network

  flyway:
    image: flyway/flyway:latest
    container_name: goGate-flyway
    command:
      - -url=jdbc:postgresql://db:5432/authdb
      - -user=postgres
      - -password=postgres
      - -locations=filesystem:/flyway/sql
      - migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
    networks:
      - goGate-network

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goGate-auth
    restart: always
    depends_on:
      - flyway
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: authdb
      AUTH_SECRET: your_secret_key
      HTTP_PORT: "8000"
    ports:
      - "8000:8000"
    networks:
      - goGate-network

volumes:
  db_data:

networks:
  goGate-network:
    driver: bridge
